# Generated by Django 5.0.7 on 2025-01-03 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'get_latest_by': 'created_at', 'ordering': ['created_at']},
        ),
    ]
